[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = []

[fmt]
line_length = 150
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "preserve"
wrap_comments = false

[rpc_endpoints]
# Arc Ecosystem (Hub Chain)
arc_testnet = "${ARC_TESTNET_RPC}"
base_testnet = "${BASE_TESTNET_RPC}"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
